"""added non-nullable constraints to db models

Revision ID: 3ba85188017
Revises: 326b787cdb4
Create Date: 2016-03-13 16:22:33.965314

"""

# revision identifiers, used by Alembic.
revision = '3ba85188017'
down_revision = '326b787cdb4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_modify_timestamp'), 'comments', ['modify_timestamp'], unique=False)
    op.alter_column('posts_category', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('posts_category', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_comments_modify_timestamp'), table_name='comments')
    ### end Alembic commands ###
